title:        imagecolorallocatefromstring
name:         imagecolorallocatefromstring
description:  imagecolorallocatefromstring is a function that will allocate a color based on a string for your PHP GD images.
author:       Andrew G. Johnson
author_email: andrew@andrewgjohnson.com
email:        andrew@andrewgjohnson.com
url:          "https://imagecolorallocatefromstring.agjgd.org"
includes_dir: .
layouts_dir:  documentation/imagecolorallocatefromstring.agjgd.org/layouts
exclude:      [
               .github,
               .github/*.md,
               .github/*.yml,
               .github/CODEOWNERS,
               .github/ISSUE_TEMPLATE,
               .github/ISSUE_TEMPLATE/*.yml,
               CHANGELOG.md,
               CNAME,
               composer.json,
               documentation/README.md,
               examples/*.php,
               examples/*.ttf,
               LICENSE,
               README.md,
               source
              ]
