title:        imagecolorallocatefromstring
name:         imagecolorallocatefromstring
description:  imagecolorallocatefromstring is a function that will allocate a color based on a string for your PHP GD images.
author:       Andrew G. Johnson
author_email: andrew@andrewgjohnson.com
email:        andrew@andrewgjohnson.com
url:          "http://imagecolorallocatefromstring.org"
includes_dir: .
layouts_dir:  documentation/imagecolorallocatefromstring.org/layouts
exclude:      [
               CHANGELOG.md,
               CNAME,
               CODE_OF_CONDUCT.md,
               composer.json,
               CONTRIBUTING.md,
               documentation/README.md,
               examples/*.php,
               examples/*.ttf,
               examples/*.txt,
               ISSUE_TEMPLATE.md,
               LICENSE,
               PULL_REQUEST_TEMPLATE.md,
               README.md,
               source
              ]